pipeline_template: ci/inmanta-tools/Jenkinsfile-integration-tests
repo_name: pytest-inmanta-lsm
lock:
    label: pytest-inmanta-lsm-iso5-dev
    variable: INMANTA_LSM_HOST
    quantity: 1
additional_constraints:
    - inmanta-lsm~=2.0.dev
env_vars:
    INMANTA_LSM_SSH_USER: rocky
    INMANTA_LSM_CONTAINER_IMAGE: code.inmanta.com:4567/solutions/containers/service-orchestrator:5-dev
    INMANTA_LSM_CONTAINER_LICENSE_FILE: /etc/inmanta/license/jenkins.inmanta.com.license
    INMANTA_LSM_CONTAINER_JWE_FILE: /etc/inmanta/license/jenkins.inmanta.com.jwe
    # only add package repo, git repo requires token and is added in the Jenkinsfile
    INMANTA_MODULE_REPO: "package:https://artifacts.internal.inmanta.com/inmanta/dev"
directories_to_lint:
    - examples
    - src
    - tests
