pipeline_template: ci/inmanta-tools/Jenkinsfile-integration-tests
repo_name: pytest-inmanta-lsm
lock:
    label: pytest-inmanta-lsm-iso4-dev
    variable: INMANTA_LSM_HOST
    quantity: 1
additional_constraints:
    - inmanta-lsm~=1.9.2.dev
env_vars:
    INMANTA_LSM_USER: rocky
    INMANTA_LSM_MODULE_CONSTRAINTS: "lsm~=2.12.0"
directories_to_lint:
    - examples
    - src
    - tests
