pipeline_template: ci/inmanta-tools/Jenkinsfile-integration-tests
repo_name: pytest-inmanta-lsm
lock:
    label: iso3-test
    variable: LOCKED_RESOURCE
    quantity: 1
directories_to_lint:
    - examples
    - src
    - tests
