pipeline_template: ci/inmanta-tools/Jenkinsfile-integration-tests
repo_name: pytest-inmanta-lsm
lock:
    label: pytest-inmanta-lsm-iso5-dev
    variable: INMANTA_LSM_HOST
    quantity: 1
additional_constraints:
    - inmanta-lsm~=2.0.dev
env_vars:
    INMANTA_LSM_USER: rocky
directories_to_lint:
    - examples
    - src
    - tests
