pipeline_template: ci/inmanta-tools/Jenkinsfile-integration-tests
repo_name: pytest-inmanta-lsm
lock:
    label: pytest-inmanta-lsm-iso4-dev
    variable: INMANTA_LSM_HOST
    quantity: 1
additional_constraints:
    - inmanta-lsm~=1.9.2.dev
env_vars:
    INMANTA_LSM_USER: rocky
    INMANTA_LSM_MODULE_CONSTRAINTS: "lsm~=2.12.0"
    INMANTA_LSM_CONTAINER_IMAGE: code.inmanta.com:4567/solutions/containers/service-orchestrator:4-dev
    INMANTA_LSM_CONTAINER_LICENSE_FILE: /etc/inmanta/license/jenkins.inmanta.com.license
    INMANTA_LSM_CONTAINER_JWE_FILE: /etc/inmanta/license/jenkins.inmanta.com.jwe
directories_to_lint:
    - examples
    - src
    - tests
